<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            path: root.cwd

        BoxLayout:
            size_hint_y: None
            height: dp(40)
            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
            Button:
                text: "Cancel"
                on_release: root.cancel()
